'use client';
import {useTranslations} from 'next-intl';
import {fields,type Row} from '@/lib/model';
export type ApartmentFilterValues=Record<string,string>;
export function matchesApartmentFilters(row:Row,values:ApartmentFilterValues){return fields.apartments.every(field=>{const value=values[field.key]??'';if(field.type==='number'){const min=values[field.key+'_min']??'',max=values[field.key+'_max']??'';if(!min&&!max)return true;const raw=row[field.key];if(raw===null||raw===undefined||raw==='')return false;const n=Number(raw);return Number.isFinite(n)&&(!min||n>=Number(min))&&(!max||n<=Number(max));}if(!value)return true;if(field.type==='checkbox')return row[field.key]===(value==='true');if(field.type==='relation'||field.key==='status'||field.key==='direction'||field.key==='currency')return String(row[field.key]??'')===value;return String(row[field.key]??'').toLocaleLowerCase().includes(value.toLocaleLowerCase());});}
export default function ApartmentFilters({rows,values,onChange,disabled}:{rows:Row[];values:ApartmentFilterValues;onChange:(values:ApartmentFilterValues)=>void;disabled:boolean}){
 const t=useTranslations();const active=Object.values(values).filter(Boolean).length;const set=(key:string,value:string)=>onChange({...values,[key]:value});
 return <details className="panel apartment-filters"><summary>{t('filters')}{active>0?' · '+active:''}</summary><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-5">{fields.apartments.filter(f=>f.key!=='project_id').map(f=>f.type==='number'?<fieldset key={f.key}><legend>{t(f.key)}</legend><div className="flex gap-2"><label className="flex-1">{t('minimum')}<input type="number" step="any" min={f.min} disabled={disabled} value={values[f.key+'_min']??''} onChange={e=>set(f.key+'_min',e.target.value)}/></label><label className="flex-1">{t('maximum')}<input type="number" step="any" min={f.min} disabled={disabled} value={values[f.key+'_max']??''} onChange={e=>set(f.key+'_max',e.target.value)}/></label></div></fieldset>:<label key={f.key}>{t(f.key)}{f.type==='checkbox'?<select disabled={disabled} value={values[f.key]??''} onChange={e=>set(f.key,e.target.value)}><option value="">{t('allValues')}</option><option value="true">{t('yes')}</option><option value="false">{t('no')}</option></select>:['status','direction','currency'].includes(f.key)?<select disabled={disabled} value={values[f.key]??''} onChange={e=>set(f.key,e.target.value)}><option value="">{t('allValues')}</option>{[...new Set(rows.map(r=>String(r[f.key]??'')).filter(Boolean))].sort().map(v=><option key={v} value={v}>{v}</option>)}</select>:<input disabled={disabled} value={values[f.key]??''} onChange={e=>set(f.key,e.target.value)}/>}</label>)}</div><button type="button" className="mt-4" disabled={disabled||!active} onClick={()=>onChange({})}>{t('resetFilters')}</button></details>;
}
