'use client';
import {useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {supabase} from '@/lib/supabase';
type Turn={role:'user'|'assistant';content:string};
export default function Assistant(){const t=useTranslations(),locale=useLocale();const [open,setOpen]=useState(false),[messages,setMessages]=useState<Turn[]>([]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false);
 async function send(e:React.FormEvent){e.preventDefault();if(busy||!draft.trim()||!consent)return;setBusy(true);setError('');const next:Turn[]=[...messages,{role:'user',content:draft.trim()}];try{const session=await supabase().auth.getSession();const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.data.session?.access_token},body:JSON.stringify({messages:next.slice(-12),locale,consent}),signal:AbortSignal.timeout(60000)});const data=await r.json();if(!r.ok){setError(t(['aiSetup','aiConsent','aiLimit'].includes(data.error)?data.error:'aiError'));return;}setMessages([...next,{role:'assistant',content:data.answer}]);setDraft('');}catch{setError(t('aiError'));}finally{setBusy(false);}}
 return <><button type="button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="crm-assistant" className="assistant-launcher fixed bottom-5 end-5 z-40 shadow-lg">✦ {t('aiAssistant')}</button>{open&&<section id="crm-assistant" role="dialog" aria-label={t('aiAssistant')} className="fixed bottom-20 end-4 z-40 bg-white border border-slate-200 rounded-2xl shadow-xl p-5 w-[420px] max-w-[calc(100vw-2rem)] max-h-[80vh] overflow-auto"><header className="flex justify-between items-center gap-3"><h2>{t('aiAssistant')}</h2><button type="button" onClick={()=>setOpen(false)} aria-label={t('close')}>×</button></header><p className="muted text-sm my-3">{t('aiIntro')}</p><div className="grid gap-3 my-4" role="log" aria-live="polite">{messages.map((m,i)=><div key={i} className={m.role==='user'?'bg-orange-50 rounded-xl p-3':'bg-slate-50 rounded-xl p-3'}><strong>{t(m.role==='user'?'chatYou':'aiAssistant')}</strong><p className="whitespace-pre-wrap mt-2" dir="auto">{m.content}</p></div>)}</div>{error&&<p role="alert" className="error my-3">{error}</p>}<form onSubmit={send}><label>{t('aiQuestion')}<textarea rows={3} maxLength={3000} value={draft} disabled={busy} onChange={e=>setDraft(e.target.value)} placeholder={t('aiExample')}/></label><label className="flex! flex-row! items-start gap-2 text-xs my-3"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/><span>{t('aiConsent')}</span></label><div className="flex justify-between gap-3"><button type="button" disabled={busy} onClick={()=>{setMessages([]);setError('');setDraft('');}}>{t('aiNew')}</button><button disabled={busy||!draft.trim()||!consent}>{t(busy?'sending':'chatSend')}</button></div></form></section>}</>;
}
