'use client';
import '@/app/messaging.css';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useLocale,useTranslations} from 'next-intl';
import {supabase} from '@/lib/supabase';
import Icon from './Icon';
import {scoped} from '@/lib/data';
import {legacyMode} from '@/lib/model';
type Contact={id:string;full_name:string};
type Thread={id:string;kind:'team'|'direct';peer_id:string|null;peer_name:string|null;last_body:string|null;last_at:string|null;unread:number};
type Message={id:string;sender_id:string;body:string;created_at:string};
const changed=()=>window.dispatchEvent(new Event('crm-chat-read'));
export function MessageLink({userId}:{userId:string}){
 const t=useTranslations(),locale=useLocale();const [unread,setUnread]=useState(0);
 useEffect(()=>{let alive=true;let pending=false;async function refresh(){if(document.hidden||pending)return;pending=true;try{const r=await supabase().rpc('crm_chat_inbox');if(alive&&!r.error){const count=(r.data as Thread[]??[]).reduce((n,c)=>n+Number(c.unread),0);setUnread(count);window.dispatchEvent(new CustomEvent('crm-chat-count',{detail:count}));}}finally{pending=false;}}refresh();const timer=setInterval(refresh,5000);window.addEventListener('crm-chat-read',refresh);document.addEventListener('visibilitychange',refresh);return()=>{alive=false;window.dispatchEvent(new CustomEvent('crm-chat-count',{detail:0}));clearInterval(timer);window.removeEventListener('crm-chat-read',refresh);document.removeEventListener('visibilitychange',refresh);};},[userId]);
 return <Link className="button chat-shortcut" href={`/${locale}/messaging`}><Icon name="chat"/>{t('messaging')}{unread>0&&<span role="status" className="chat-unread" aria-label={t('chatUnread',{count:unread})}>{unread>99?'99+':unread}</span>}</Link>;
}
export function WorkNotifications({userId}:{userId:string}){
 useEffect(()=>{let alive=true,pending=false;async function refresh(){if(document.hidden||pending)return;pending=true;try{const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const appointments=scoped('appointments',userId,'id',{count:'exact',head:true});
 const tasks=scoped('tasks',userId,'id',{count:'exact',head:true});
 const results=await Promise.all([legacyMode?appointments.eq('appointment_date',today).or('status.is.null,status.not.in.(cancelled,completed,canceled,Annulé,Terminé)'):appointments.gte('starts_at',today+'T00:00:00+03:00').lt('starts_at',today+'T23:59:59+03:00').or('status.is.null,status.not.in.(cancelled,completed)'),legacyMode?tasks.eq('completed',false).lte('due_date',today):tasks.lte('due_at',new Date().toISOString()).or('status.is.null,status.not.in.(completed,done,cancelled)')]);
 if(alive)results.forEach((r,i)=>{if(!r.error)window.dispatchEvent(new CustomEvent('crm-work-count',{detail:{entity:i===0?'appointments':'tasks',count:r.count??0}}));});
 }finally{pending=false;}}void refresh();const timer=setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);window.addEventListener('focus',refresh);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('focus',refresh);['appointments','tasks'].forEach(entity=>window.dispatchEvent(new CustomEvent('crm-work-count',{detail:{entity,count:0}})));};},[userId]);return null;
}
export default function Messaging({userId}:{userId:string}){
 const t=useTranslations(),locale=useLocale();const [contacts,setContacts]=useState<Contact[]>([]),[threads,setThreads]=useState<Thread[]>([]),[selected,setSelected]=useState(''),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[peer,setPeer]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[opening,setOpening]=useState(false),[error,setError]=useState(''),[setup,setSetup]=useState(false),[limit,setLimit]=useState(100),[search,setSearch]=useState('');const scroll=useRef<HTMLDivElement>(null),request=useRef(0),nearBottom=useRef(true);
 const title=(c:Thread)=>c.kind==='team'?t('chatTeam'):c.peer_name||t('chatFormerMember');
 const refreshInbox=useCallback(async()=>{const r=await supabase().rpc('crm_chat_inbox');if(r.error)throw r.error;setThreads(r.data as Thread[]??[]);return r.data as Thread[]??[];},[]);
 useEffect(()=>{let alive=true;async function init(){try{const [d,i]=await Promise.all([supabase().rpc('crm_chat_directory'),supabase().rpc('crm_chat_inbox')]);if(d.error||i.error)throw d.error||i.error;if(!alive)return;setContacts(d.data as Contact[]??[]);const rows=i.data as Thread[]??[];setThreads(rows);setSelected(rows.find(c=>c.kind==='team')?.id??rows[0]?.id??'');}catch(e){if(alive){const code=(e as {code?:string}).code;setSetup(code==='PGRST202'||code==='42P01');setError(t(code==='PGRST202'||code==='42P01'?'chatSetup':'chatLoadError'));}}finally{if(alive)setLoading(false);}}init();return()=>{alive=false;};},[userId,t]);
 useEffect(()=>{if(setup)return;let busy=false,alive=true;async function poll(){if(document.hidden||busy)return;busy=true;try{const [d,i]=await Promise.all([supabase().rpc('crm_chat_directory'),supabase().rpc('crm_chat_inbox')]);if(alive&&!d.error&&!i.error){setContacts(d.data as Contact[]??[]);setThreads(i.data as Thread[]??[]);}}finally{busy=false;}}const timer=setInterval(poll,10000);document.addEventListener('visibilitychange',poll);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',poll);};},[setup,userId]);
 useEffect(()=>{if(!selected)return;let alive=true,busy=false;const generation=++request.current;setMessages([]);nearBottom.current=true;async function fetch(){if(document.hidden||busy)return;busy=true;try{const r=await supabase().from('crm_chat_messages').select('id,sender_id,body,created_at').eq('thread_id',selected).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(limit);if(r.error)throw r.error;if(!alive||generation!==request.current)return;const rows=(r.data as Message[]).reverse();setMessages(rows);if(rows.length&&document.hasFocus()&&!document.hidden){const read=await supabase().rpc('crm_chat_mark_read',{thread:selected,message:rows[rows.length-1].id});if(read.error)throw read.error;if(alive){await refreshInbox();changed();}}}catch{if(alive)setError(t('chatLoadError'));}finally{busy=false;}}fetch();const timer=setInterval(fetch,5000);window.addEventListener('focus',fetch);document.addEventListener('visibilitychange',fetch);return()=>{alive=false;request.current++;clearInterval(timer);window.removeEventListener('focus',fetch);document.removeEventListener('visibilitychange',fetch);};},[selected,limit,refreshInbox,t]);
 useEffect(()=>{if(scroll.current&&nearBottom.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[messages]);
 function choose(id:string){if(sending||opening)return;setSelected(id);setDraft('');setLimit(100);setError('');}
 async function start(){if(!peer||opening||sending)return;setOpening(true);setError('');try{const r=await supabase().rpc('crm_chat_open',{peer});if(r.error)throw r.error;await refreshInbox();setSelected(String(r.data));setDraft('');setLimit(100);setPeer('');}catch{setError(t('chatOpenError'));}finally{setOpening(false);}}
 async function send(e:React.FormEvent){e.preventDefault();const body=draft.trim();if(!body||sending||!selected)return;setSending(true);setError('');const threadId=selected;try{const r=await supabase().from('crm_chat_messages').insert({thread_id:threadId,sender_id:userId,body}).select('id,sender_id,body,created_at').single();if(r.error)throw r.error;const msg=r.data as Message;setMessages(rows=>[...rows,msg]);nearBottom.current=true;setDraft('');await supabase().rpc('crm_chat_mark_read',{thread:threadId,message:msg.id});await refreshInbox();changed();}catch{setError(t('chatSendError'));}finally{setSending(false);}}
 const active=threads.find(c=>c.id===selected);
 return <><div className="page-heading"><div><h1>{t('messaging')}</h1><p className="muted">{t('chatIntro')}</p></div></div>{error&&<p className="error" role="alert">{error}</p>}{loading?<p role="status">{t('loading')}</p>:setup?<section className="panel"><p>{t('chatSetupHelp')}</p></section>:<div className="messaging"><section className="panel chat-sidebar"><h2>{t('chatConversations')}</h2><label>{t('chatNew')}<select value={peer} onChange={e=>setPeer(e.target.value)} disabled={opening||sending}><option value="">{t('select')}</option>{contacts.filter(c=>c.id!==userId).map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><button onClick={start} disabled={!peer||opening||sending}>{t(opening?'loading':'chatOpen')}</button><label>{t('search')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="chat-thread-list">{threads.filter(c=>title(c).toLocaleLowerCase(locale).includes(search.toLocaleLowerCase(locale))).map(c=><button className={`chat-thread ${c.id===selected?'selected':''}`} key={c.id} disabled={sending||opening} onClick={()=>choose(c.id)} aria-pressed={c.id===selected}><span className="chat-thread-heading"><strong>{title(c)}</strong>{Number(c.unread)>0&&<span className="chat-unread" aria-label={t('chatUnread',{count:Number(c.unread)})}>{c.unread}</span>}</span><small>{c.last_body?.slice(0,80)||t('chatNoMessages')}</small></button>)}</div></section><section className="panel chat-conversation"><header><h2>{active?title(active):t('chatChoose')}</h2><p className="muted">{active?.kind==='team'?t('chatTeamHelp'):t('chatPrivateHelp')}</p></header><div className="chat-messages" ref={scroll} onScroll={()=>{const el=scroll.current;if(el)nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;}} aria-label={t('chatMessages')}>{messages.length>=limit&&limit<1000&&<button className="chat-older" onClick={()=>{nearBottom.current=false;setLimit(n=>n+100);}}>{t('chatOlder')}</button>}{!messages.length&&<p className="muted">{t('chatNoMessages')}</p>}{messages.map(m=><article className={`chat-message ${m.sender_id===userId?'mine':''}`} key={m.id}><strong>{m.sender_id===userId?t('chatYou'):contacts.find(c=>c.id===m.sender_id)?.full_name||t('chatFormerMember')}</strong><p dir="auto">{m.body}</p><time dateTime={m.created_at}>{new Intl.DateTimeFormat(locale,{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Jerusalem'}).format(new Date(m.created_at))}</time></article>)}</div><form className="chat-compose" onSubmit={send}><label>{t('chatWrite')}<textarea value={draft} maxLength={4000} disabled={!selected||sending} onChange={e=>setDraft(e.target.value)} rows={3}/></label><div><small className="muted">{draft.length}/4000</small><button disabled={!selected||sending||!draft.trim()}>{t(sending?'sending':'chatSend')}</button></div></form></section></div>}</>;
}
