'use client';
import {useLocale,useTranslations} from 'next-intl';
import {cents,total,deliveryBalance,type PaymentTemplate,type PaymentLine} from '@/lib/payment-template';
export default function PaymentSheet({title,value,onChange}:{title:string;value:PaymentTemplate;onChange?:(value:PaymentTemplate)=>void}){
 const t=useTranslations();const locale=useLocale();const editable=Boolean(onChange);try{value=deliveryBalance(value);}catch{value={...value,delivery:[{label:'',ils:'',eur:''}]};}
 function amount(raw:string){try{const number=cents(raw);return number===null?'—':new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(number/100);}catch{return t('amountInvalid');}}
 function sum(rows:PaymentLine[],currency:'ils'|'eur'){try{const number=total(rows,currency);return number===null?'—':new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(number/100);}catch{return t('amountInvalid');}}
 function change(key:keyof PaymentTemplate,text:string){onChange?.({...value,[key]:text});}
 function cell(raw:string,label:string,action:(text:string)=>void,money=false){return editable?<input type="text" inputMode={money?'decimal':undefined} value={raw} aria-label={label} placeholder={money?'—':t('fillValue')} maxLength={money?30:500} onChange={e=>action(e.target.value)}/>:<span>{money?amount(raw):raw||'—'}</span>;}
 return <div className="payment-sheet-scroll"><div className="payment-sheet" dir={locale==='he'?'rtl':'ltr'}><div className="sheet-heading">{title||t('title')}</div>{value.exchangeRate&&value.exchangeDate&&<p className="sheet-notes">{t('exchangeInfo',{rate:value.exchangeRate,date:new Date(value.exchangeDate).toLocaleDateString(locale,{timeZone:'Asia/Jerusalem'})})}</p>}<table><caption className="sr-only">{t('paymentTerms')}</caption><thead><tr><th>{t('propertyDescription')}</th><th dir="ltr">₪</th><th dir="ltr">€</th></tr></thead><tbody><tr><td>{cell(value.property,t('propertyDescription'),text=>change('property',text))}</td><td>{cell(value.priceIls,t('propertyPrice')+' ₪',text=>change('priceIls',text),true)}</td><td><span>{amount(value.priceEur)}</span></td></tr></tbody></table>{(['signature','delivery','fees'] as const).map(group=><section key={group} className={`sheet-group sheet-${group}`}><h3>{t(group)}</h3><table><thead className="sr-only"><tr><th>{t('paymentLabel')}</th><th>₪</th><th>€</th></tr></thead><tbody>{value[group].map((row,i)=><tr key={i}><td>{row.label||t(group==='delivery'?'delivery':'paymentInstallment',group==='delivery'?{}:{number:i+1})}</td>{(['ils','eur'] as const).map(currency=><td key={currency} dir="ltr"><span className="sheet-currency">{currency==='ils'?'₪':'€'}</span>{(currency==='eur'||group==='delivery')?<span>{amount(row[currency])}</span>:cell(row[currency],t(group)+` ${i+1} ${currency==='ils'?'₪':'€'}`,text=>onChange?.({...value,[group]:value[group].map((line,index)=>index===i?{...line,[currency]:text}:line)}),true)}</td>)}</tr>)}<tr className="sheet-total"><th scope="row">{t(group==='fees'?'totalFees':group==='signature'?'totalSignature':'totalDelivery')}</th><td dir="ltr">₪ {sum(value[group],'ils')}</td><td dir="ltr">€ {sum(value[group],'eur')}</td></tr></tbody></table>{false&&<button type="button" className="sheet-add" onClick={()=>onChange?.({...value,[group]:[...value[group],{label:'',ils:'',eur:''}]})}>+ {t('addPaymentLine')}</button>}</section>)}{editable?<label className="sheet-notes">{t('notes')}<textarea value={value.notes} onChange={e=>change('notes',e.target.value)} maxLength={10000}/></label>:value.notes&&<p className="sheet-notes whitespace-pre-wrap">{value.notes}</p>}</div></div>;
}
