'use client';
import {useState} from 'react';
import {useTranslations} from 'next-intl';
import {supabase} from '@/lib/supabase';
import {parseLeads,splitDelimited,type ImportLead} from '@/lib/prospect-import';
import type {Row} from '@/lib/model';
type Member={id:string;full_name:string;active:boolean};
export default function ProspectImport({members,prospects,onImported}:{members:Member[];prospects:Row[];onImported:()=>Promise<void>}){
 const t=useTranslations();const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());
 const [matrix,setMatrix]=useState<string[][]>([]),[filename,setFilename]=useState(''),[year,setYear]=useState(2026),[fallback,setFallback]=useState(today.toISOString().slice(0,10)),[mapping,setMapping]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 let preview:ImportLead[]=[],previewError='';try{if(matrix.length)preview=parseLeads(matrix,year,fallback,prospects.map(p=>({email:p.email,phone:p.phone})));}catch{previewError=t('importHeadersError');}
 const names=[...new Set(preview.map(p=>p.commercial))];const valid=preview.filter(p=>!p.issue&&!p.duplicate);const mapped=names.every(n=>mapping[n]!==undefined);
 async function read(file:File|undefined){if(!file)return;setBusy(true);setMatrix([]);setFilename('');setError('');setMessage('');setMapping({});try{
  if(file.size>5*1024*1024)throw new Error('size');let data:string[][];
  if(/\.xlsx$/i.test(file.name)){
   const {Workbook}=await import('exceljs');const wb=new Workbook();await wb.xlsx.load(await file.arrayBuffer() as Parameters<typeof wb.xlsx.load>[0]);const sheet=wb.worksheets[0];if(!sheet||sheet.rowCount>5001||sheet.columnCount>50)throw new Error('size');data=[];
   sheet.eachRow({includeEmpty:true},row=>{const values:string[]=[];row.eachCell({includeEmpty:true},(cell,col)=>{const v=cell.value;if(v&&typeof v==='object'&&('formula' in v||'sharedFormula' in v))throw new Error('formula');values[col-1]=v instanceof Date?v.toISOString():typeof v==='object'&&v!==null?'richText' in v?v.richText.map(r=>r.text).join(''):'text' in v?String(v.text):'':String(v??'');});data[row.number-1]=values;});
   data=Array.from({length:data.length},(_,i)=>data[i]??[]);const header=data.find(r=>r.some(s=>s.trim()))??[];const time=header.findIndex(h=>/^(heure|time)$/i.test(h.trim()));if(time>=0)for(const row of data.slice(1)){if(row[time]?.includes('T'))row[time]=row[time].slice(11,19);else if(row[time]&&Number(row[time])>=0&&Number(row[time])<1){const seconds=Math.round(Number(row[time])*86400);row[time]=`${String(Math.floor(seconds/3600)%24).padStart(2,'0')}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}}
  }else if(/\.(csv|tsv|txt)$/i.test(file.name)){const text=await file.text();const first=text.split(/\r?\n/)[0];data=splitDelimited(text,first.includes('\t')?'\t':first.includes(';')?';':',');}else throw new Error('format');
  if(data.length>5001||data.some(r=>r.length>50))throw new Error('size');const rows=parseLeads(data,year,fallback,prospects.map(p=>({email:p.email,phone:p.phone})));if(!rows.length)throw new Error('empty');setMatrix(data);setFilename(file.name);
 }catch{setError(t('importFileError'));}finally{setBusy(false);}}
 async function confirm(){if(busy||!valid.length||!mapped)return;setBusy(true);setError('');setMessage('');try{
  const result=await supabase().rpc('crm_import_prospects',{filename,leads:valid.map(p=>({...p,assigned_to:mapping[p.commercial]||null}))});if(result.error)throw result.error;
  setMatrix([]);setFilename('');await onImported();setMessage(t('importSuccess',{imported:result.data.imported,skipped:result.data.skipped}));
 }catch{setError(t('importSaveError'));}finally{setBusy(false);}}
 return <section className="panel"><h2>{t('importProspects')}</h2><p className="muted">{t('importHelp')}</p><div className="grid sm:grid-cols-3 gap-4 my-5"><label>{t('importFile')}<input type="file" accept=".xlsx,.csv,.tsv,.txt" disabled={busy} onChange={e=>{read(e.target.files?.[0]);e.target.value='';}}/></label><label>{t('importYear')}<input type="number" min="1900" max="2200" value={year} disabled={busy} onChange={e=>setYear(Number(e.target.value))}/></label><label>{t('importFallbackDate')}<input type="date" value={fallback} disabled={busy} onChange={e=>setFallback(e.target.value)}/></label></div>{(error||previewError)&&<p className="error" role="alert">{error||previewError}</p>}{message&&<p className="success" role="status">{message}</p>}{busy&&<p role="status">{t('loading')}</p>}{preview.length>0&&<><p>{filename} · {t('importSummary',{valid:valid.length,duplicates:preview.filter(p=>p.duplicate).length,invalid:preview.filter(p=>p.issue).length})}</p><div className="grid sm:grid-cols-3 gap-4 my-5">{names.map(n=><label key={n}>{n||t('unassigned')}<select value={mapping[n]??'pending'} disabled={busy} onChange={e=>setMapping(m=>({...m,[n]:e.target.value}))}><option value="pending" disabled>{t('select')}</option><option value="">{t('unassigned')}</option>{members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label>)}</div><div className="prospect-list-scroll"><table className="prospect-list"><thead><tr><th>{t('importLine')}</th><th>{t('name')}</th><th>{t('email')}</th><th>{t('phone')}</th><th>{t('receivedOn')}</th><th>{t('importReview')}</th></tr></thead><tbody>{preview.map(p=><tr key={p.line}><td>{p.line}</td><td>{p.name}</td><td><bdi>{p.email}</bdi></td><td><bdi>{p.phone}</bdi></td><td><bdi>{p.received_on} {p.received_time}</bdi></td><td>{p.issue?t('importInvalid')+' · '+p.issue:p.duplicate?t('importDuplicate'):t(p.swapped?'importSwapped':'importReady')}</td></tr>)}</tbody></table></div><p className="muted my-4">{t('importIgnoredHelp')}</p><button disabled={busy||!valid.length||!mapped||!Number.isInteger(year)||year<1900||year>2200} onClick={confirm}>{t('confirmImport',{count:valid.length})}</button></>}</section>;
}

