'use client';
import {useEffect,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {entities} from '@/lib/model';
import Icon from './Icon';
export default function Shell({children}:{children:React.ReactNode}) {
 const t=useTranslations();const locale=useLocale();const path=usePathname();const tail=path.split('/').slice(2).join('/');
 const [collapsed,setCollapsed]=useState(false);
 useEffect(()=>{try{setCollapsed(localStorage.getItem('yi-sidebar-collapsed')==='true');}catch{}},[]);
 function toggleSidebar(){setCollapsed(previous=>{const next=!previous;try{localStorage.setItem('yi-sidebar-collapsed',String(next));}catch{}return next;});}
 const active=tail==='messaging'?'messaging':tail==='administration'?'administration':tail==='payment-terms'?'paymentTerms':entities.find(e=>tail.startsWith(e))??'dashboard';
 return <div className={`app-shell ${collapsed?'sidebar-collapsed':''}`}><aside className="sidebar"><button type="button" className="sidebar-toggle" onClick={toggleSidebar} aria-expanded={!collapsed} aria-controls="sidebar-navigation" aria-label={t(collapsed?'expandSidebar':'collapseSidebar')} title={t(collapsed?'expandSidebar':'collapseSidebar')}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d={collapsed?'m9 6 6 6-6 6':'m15 6-6 6 6 6'}/></svg></button><Link className="brand" href={`/${locale}`}><div className="brand-symbol" aria-hidden="true">Y<span>.</span></div><div><span className="brand-name">YONATHAN</span><span className="brand-subtitle">IMMOBILIER</span></div></Link><div className="nav-caption">{t('workspace')}</div><nav id="sidebar-navigation" className="navitems" aria-label={t('navigation')}><Link className={`navlink ${tail===''?'active':''}`} aria-current={tail===''?'page':undefined} title={t('dashboard')} href={`/${locale}`}><Icon name="dashboard"/><span>{t('dashboard')}</span><span className="nav-dot"/></Link>{entities.map(e=><Link key={e} className={`navlink ${tail.startsWith(e)?'active':''}`} aria-current={tail.startsWith(e)?'page':undefined} title={t(e)} href={`/${locale}/${e}`}><Icon name={e}/><span>{t(e)}</span><span className="nav-dot"/></Link>)}<Link className={`navlink ${tail==='payment-terms'?'active':''}`} aria-current={tail==='payment-terms'?'page':undefined} title={t('paymentTerms')} href={`/${locale}/payment-terms`}><Icon name="payments"/><span>{t('paymentTerms')}</span><span className="nav-dot"/></Link><Link className={`navlink ${tail==='messaging'?'active':''}`} aria-current={tail==='messaging'?'page':undefined} title={t('messaging')} href={`/${locale}/messaging`}><Icon name="chat"/><span>{t('messaging')}</span><span className="nav-dot"/></Link></nav><div className="sidebar-footer"><div className="footer-monogram">YI</div><div><strong>Yonathan Immobilier</strong><span>{t('workspace')}</span></div></div></aside><main className="main"><header className="topbar"><div className="breadcrumb"><span>Yonathan</span><span className="breadcrumb-divider">/</span><strong>{t(active)}</strong></div><nav aria-label={t('language')} className="language-switch">{['fr','he','en'].map(l=><Link key={l} aria-label={({fr:'Français',he:'עברית',en:'English'})[l]} title={({fr:'Français',he:'עברית',en:'English'})[l]} aria-current={locale===l?'page':undefined} className={locale===l?'selected':''} href={`/${l}/${tail}`}>{({fr:'FR',he:'HE',en:'EN'})[l]}</Link>)}</nav></header><div className="content-area">{children}</div></main></div>;
}


